### ISSUE TITLE
PScout cannot find compiled classes when run for API 23 and I there is also a an ArrayIndexOutOfBounds exception 

### ISSUE THREAD

**Issue by tpetsas** [zyrikby/PScout#1]
I have downloaded the source code of Android 6.0 (API 23) and I compiled it
using the lunch full-eng option.

`$ cd PScout`
`$ source bin/setup_env`

`$ mkdir Android_class_dir`
`$ cd Android_class_dir/`
`$ ../bin/setupanalysis.sh ../../AOSP/Android6.0/`

Setting up analysis...
Getting relevant .class files...
???Cannot find compiled classes for webview/webview??????Cannot find compiled classes for LatinIME/LatinIME??????Cannot find compiled classes for Camera2/Camera2??????Cannot find compiled classes for messaging/messaging??????Cannot find  >compiled classes for Gallery2/Gallery2??????Cannot find compiled classes for Email/Email??????Cannot find compiled classes for DeskClock/DeskClock??????Cannot find compiled classes for Browser/Browser??????Cannot find compiled classes   >for LiveWallpapers/LiveWallpapers??????Cannot find compiled classes for Calendar/Calendar??????Cannot find compiled classes for OpenWnn/OpenWnn??????Cannot find compiled classes for Music/Music??????Cannot find compiled classes for      >Bluetooth/Bluetooth??????Cannot find compiled classes for PhotoTable/PhotoTable??????Cannot find compiled classes for DocumentsUI/DocumentsUI??????Cannot find compiled classes for QuickSearchBox/QuickSearchBox??????Cannot find compiled  >classes for PrintSpooler/PrintSpooler??????Cannot find compiled classes for CertInstaller/CertInstaller??????Cannot find compiled classes for Exchange2/Exchange2??????Cannot find compiled classes for Galaxy4/Galaxy4??????Cannot find     >compiled classes for LiveWallpapersPicker/LiveWallpapersPicker??????Cannot find compiled classes for DownloadProviderUi/DownloadProviderUi??????Cannot find compiled classes for SoundRecorder/SoundRecorder??????Cannot find compiled       >classes for Calculator/Calculator??????Cannot find compiled classes for Development/Development??????Cannot find compiled classes for KeyChain/KeyChain??????Cannot find compiled classes for NoiseField/NoiseField??????Cannot find         >compiled classes for PhaseBeam/PhaseBeam??????Cannot find compiled classes for HoloSpiralWallpaper/HoloSpiralWallpaper??????Cannot find compiled classes for CaptivePortalLogin/CaptivePortalLogin??????Cannot find compiled classes for     >BasicDreams/BasicDreams??????Cannot find compiled classes for UserDictionaryProvider/UserDictionaryProvider??????Cannot find compiled classes for PicoTts/PicoTts??????Cannot find compiled classes for HTMLViewer/HTMLViewer??????Cannot    >find compiled classes for BluetoothMidiService/BluetoothMidiService??????Cannot find compiled classes for PacProcessor/PacProcessor??????Cannot find compiled classes for Provision/Provision??????Cannot find compiled classes for          >WAPPushManager/WAPPushManager??????Cannot find compiled classes for appops???
???Cannot find compiled classes for settings???
???Cannot find compiled classes for services???
???Cannot find compiled classes for media_cmd???
???Cannot find compiled classes for svc???
???Cannot find compiled classes for javax.obex???
???Cannot find compiled classes for appwidget???
???Cannot find compiled classes for ime???
???Cannot find compiled classes for am???
???Cannot find compiled classes for wm???
???Cannot find compiled classes for bu???
???Cannot find compiled classes for telecom???
???Cannot find compiled classes for com.android.mediadrm.signer???
???Cannot find compiled classes for uiautomator???
???Cannot find compiled classes for pm???
???Cannot find compiled classes for dpm???
???Cannot find compiled classes for com.android.future.usb.accessory???
???Cannot find compiled classes for sm???
???Cannot find compiled classes for bmgr???
???Cannot find compiled classes for content???
???Cannot find compiled classes for hid???
???Cannot find compiled classes for requestsync???
???Cannot find compiled classes for ethernet-service???
???Cannot find compiled classes for com.android.location.provider???
???Cannot find compiled classes for wifi-service???
???Cannot find compiled classes for input???
???Cannot find compiled classes for monkey???
Parsing AndroidManifest.xml files...
Generating 3rd party permission list...  
Copying current.txt...

Please run the following line to test setup:
runsoot dump.DumpClass com.android.internal.telephony.gsm.GSMPhone
If no error, please run the following line to start analysis:
../bin/dumpclass.sh

When I run the suggested command to test the setup I'm getting this:
`$ runsoot dump.DumpClass com.android.internal.telephony.gsm.GSMPhone`

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 200
        at dump.FindPermissionString.loadPermissions(FindPermissionString.java:62)
        at dump.FindPermissionString.<init>(FindPermissionString.java:83)
        at dump.DumpClass.main(DumpClass.java:45)

**Comment by zyrikby** [comment]
@tpetsas I am not a developer of PScout, I've just used it to generate mappings. You should contact developers of this tool about this issue.

**Comment by tpetsas** [comment]
Thank you for the response!
I have already contacted them, but I have not received any response yet..
