### ISSUE TITLE
Generated result in excel format 

### ISSUE THREAD

**Issue by smartarams** [zyrikby/PScout#3]
Hi Yury, 

You've done great work here and its the most complete mapping Ive come across. Can you please convert the generated result to excel or tab separated format. 

Thanks.

**Comment by zyrikby** [comment]
Hi,
This is the format of PScout. I've just used their tool to generate mappings for different API versions. The authors of PScout produced its new version and generated some mappings in csv format. You can download them here: http://pscout.csl.toronto.edu/downloads.php

In my case, I needed the mappings for Androguard project. I am quite busy now to write code for transformations, but if you need you can see the tool I developed to transform mappings.  Check the code here: https://github.com/androguard/androguard/blob/master/tools/permissions/extract_api_permission_mappings.py 
Using it you can easily develop a transformer into your required format.

**Comment by smartarams** [comment]
Thanks Yury,

I'm not so familiar with coding so I guess I will try find an alternative,
but the interesting part is that your mapping contains more api's than the
one on  http://pscout.csl.toronto.edu/downloads.php Is there an explanation
for that?

Sorry for bugging you.

On Wed, May 4, 2016 at 1:51 PM, Yury Zhauniarovich <notifications@github.com

**Comment by zyrikby** [comment]
I do not know why this happened. Most probably, their redeveloped their tool and now the output has changed. 

If this is not a secret, can you tell why you need these mappings then in csv format? Till now I saw only one reason of having these mappings , is to implement tools for checking app permissions. But once you're not a developer, then I do not see the reason to pay attention to these projects.
