### ISSUE TITLE
[Question] What is the meaning of the number inside the brackets?

### ISSUE THREAD

**Issue by FrankieYin** [zyrikby/PScout#4]
Hi @zyrikby ,

I understand this project is 3 years old but I'm doing a project on permission flow and needed to check API to permission mappings from PScout and therefore came across your repo.
When I look into the `results/API_22/allmappings` file, I didn't quite get the meaning of the numbers inside the brackets, for example:
`<android.content.pm.IPackageManager$Stub: boolean onTransact(int,android.os.Parcel,android.os.Parcel,int)> (2)`
At first I thought it means argument count but then the arguments are part of the signature and the number clearly does not match.

Would you kindly tell me what's the meaning of those numbers?

Kind regards,
Zhijun

**Comment by zyrikby** [comment]
Good question! I really do not know because I am not a developer of this tool. I just use it to create these mappings. Please, contact the authors of the tool: [link](https://security.csl.toronto.edu/pscout/)
