### ISSUE TITLE
Playdrone Apps

### ISSUE THREAD

**Issue by SanondaDattaGupta** [zyrikby/PScout#5]
Hi can you kindly runt he tool for playdrone app? I do not have linux machine. 
here is the link:
https://archive.org/details/playdrone-apk-e8
it would be very kind of you, if you kindly do it.
Thank you!

**Comment by zyrikby** [comment]
@SanondaDattaGupta PScout cannot run with apps, it is used to create a mapping between Android Framework API calls and permissions.
